from .user_table_model import UserTableModel
from .role_table_model import RoleTableModel
from .role_permission_table_model import RolePermissionTableModel
from .unit_table_model import UnitTableModel
from .partner_table_model import PartnerTableModel
from .academic_year_table_model import AcademicYearTableModel
from .fund_source_table_model import FundSourceTableModel
from .role_permission_table_model import RolePermissionTableModel
